name: atlasgr_commercial
version: "1.0.0"
config-version: 2
profile: atlasgr_commercial
model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  atlasgr_commercial:
    +materialized: table
